const API_CONST = {
  N_USER_SIGNUP: "N_USER_SIGNUP",
  N_USER_SIGNUP_FB: "N_USER_SIGNUP_FB",

  N_SERVICE_PREF: "N_SERVICE_PREF",
  N_SELECT_KIDS: "N_SELECT_KIDS",
  N_GET_BRANDS_LIST: "N_GET_BRANDS",
  N_SELECT_WHO_WILL_DECIDE: "N_SELECT_WHO_WILL_DECIDE",
  N_GET_SIZES: "N_GET_SIZES",
  N_NEW_GET_SIZES: "N_NEW_GET_SIZES",
  N_NEW_GET_BRANDS_LIST: "N_NEW_GET_BRANDS_LIST",

  N_SELECT_SIZE_AND_PROPORTION: "N_SELECT_SIZE_AND_PROPORTION",
  N_SEND_BRANDS_DATA: "N_SEND_BRANDS_DATA",
  N_DOB_SELECT: "N_DOB_SELECT",
  N_DUEDATE_SELECT: "N_DUEDATE_SELECT",
  N_GET_STYLE_LIST: "N_GET_STYLE_LIST",
  N_SEND_FEEDBACK: "N_SEND_FEEDBACK",
  N_GET_BOX_STYLE_LIST: "N_GET_BOX_STYLE_LIST",
  N_MAKE_PAYMENT: "N_MAKE_PAYMENT",
  N_GIFT_PAYMENT: "N_GIFT_PAYMENT",

  N_GIFT_AFTER_LOGIN: "N_GIFT_AFTER_LOGIN",

  N_ACTIVE_SUBSCRIPTION: "N_ACTIVE_SUBSCRIPTION",
  N_CANCLE_SUBSCRIPTION: "N_CANCLE_SUBSCRIPTION",

  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_FB: "LOGIN_USER_FB",

  GET_PROFILE_DATA: "GET_PROFILE_DATA",
  GET_LAST_BOX_DATA: "GET_LAST_BOX_DATA",
  UPDATE_AVATAR: "UPDATE_AVATAR",
  N_GET_STYLE_LIST_NEW: "N_GET_STYLE_LIST_NEW",
  N_BILLING_INFO_SELECT: "N_BILLING_INFO_SELECT",
  N_BILLING_SHIPPING_INFO_SELECT: "N_BILLING_SHIPPING_INFO_SELECT",
  N_STYLE_INFO_SELECT: "N_STYLE_INFO_SELECT",
  N_STYLE_INFO_SELECT_NEW: "N_STYLE_INFO_SELECT_NEW",

  N_CHECK_SCREEN_SELECT: "N_CHECK_SCREEN_SELECT",
  N_CHECK_INFO_SELECT: "N_CHECK_INFO_SELECT",
  N_VERIFY_EMAIL: "N_VERIFY_EMAIL",
  N_VERIFY_EMAIL_GIFT: "N_VERIFY_EMAIL_GIFT",

  N_ADD_REFREL: "N_ADD_REFREL",
  N_GET_REFREL: "N_GET_REFREL",
  N_SOCIAL_INFO: "N_SOCIAL_INFO",

  N_DELETE_KID: "N_DELETE_KID",
  N_KID_LIST: "N_KID_LIST",
  N_KID_AVATAR: "N_KID_AVATAR",
  N_CHECK_REFERRAL: "N_CHECK_REFERRAL",
  _GET_PROFILE_DATA: "_GET_PROFILE_DATA",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  N_ORDER_HISTORY: "N_ORDER_HISTORY",
  ORDER_HISTORY: "ORDER_HISTORY",
  N_CHECK_OUT: "N_CHECK_OUT",
  N_FORGOT_PASSWORD: "N_FORGOT_PASSWORD",
  N_UPDATE_KID: "N_UPDATE_KID",
  N_UPDATE_USER_PROFILE: "N_UPDATE_USER_PROFILE",

  N_CHANGE_PASSWORD: "N_CHANGE_PASSWORD",
  N_GET_CREDIT_LIST: "N_GET_CREDIT_LIST",
  N_CHECK_REFERRAL_CODE: "N_CHECK_REFERRAL_CODE",
  N_SIZE_SWAP: "N_SIZE_SWAP",
  N_REDEEM_AMOUNT: "N_REDEEM_AMOUNT",
  N_USER_REDEEM_POINTS: "N_USER_REDEEM_POINTS",

  N_USER_RESET_PROFILE_PIC: "N_USER_RESET_PROFILE_PIC",
  N_UPDATE_B0X_FREQ: "N_UPDATE_B0X_FREQ",
  N_REQUEST_BOX: "N_REQUEST_BOX",

  N_GET_ALL_PROPERTY_LIST: "N_GET_ALL_PROPERTY_LIST",

  N_GET_SAVED_PROPERTY_LIST: "N_GET_SAVED_PROPERTY_LIST",

  N_GET_PROPERTY_DETAIL: "N_GET_PROPERTY_DETAIL",

  N_GET_FILTERED_PROPERTY_LIST: "N_GET_FILTERED_PROPERTY_LIST",

  N_LOGOUT: "N_LOGOUT",
  N_RESET_PROPERTY_LIST_RESPONSE: "N_RESET_PROPERTY_LIST_RESPONSE",
  N_SEARCH_CRITERIA: "N_SEARCH_CRITERIA",
  N_CLEAR_SEARCH_CRITERIA: "N_CLEAR_SEARCH_CRITERIA",

  //Contacts

  N_GET_ACCEEPTED_CONTACT_LIST: "N_GET_ACCEEPTED_CONTACT_LIST",
  N_GET_PENDING_CONTACT_LIST: "N_GET_PENDING_CONTACT_LIST",
  N_GET_REJECTED_CONTACT_LIST: "N_GET_REJECTED_CONTACT_LIST",

  //Inspections
  N_POST_INSEPECTON_REQUEST: "N_POST_INSEPECTON_REQUEST",
  N_POST_BOOK_INSEPECTON_TIME_SLOT_REQUEST:
    "N_POST_BOOK_INSEPECTON_TIME_SLOT_REQUEST",
  N_GET_UPCOMING_INSPECTION_LIST: "N_GET_UPCOMING_INSPECTION_LIST",
  N_GET_PENDING_INSPECTION_LIST: "N_GET_PENDING_INSPECTION_LIST",
  N_GET_DECLINED_INSPECTION_LIST: "N_GET_DECLINED_INSPECTION_LIST",

  //Settings
  N_GET_NOTIFICATION_SETTING: "N_GET_NOTIFICATION_SETTING",

  //KnowlegdeBase
  N_GET_KNOWLEDGE_BASE_LIST: " N_GET_KNOWLEDGE_BASE_LIST",

  //KnowlegdeDetail
  N_GET_KNOWLEDGE_DETAIL: " N_GET_KNOWLEDGE_DETAIL",

  //Service
  N_GET_SERVICE_LIST: " N_GET_SERVICE_LIST",

  //Notification List
  N_GET_NOTIFICATION_LIST: " N_GET_NOTIFICATION_LIST",

  //Payment Report List
  N_GET_PAYMENT_REPORT_LIST: " N_GET_PAYMENT_REPORT_LIST",

  //GET CHAT HISTORY
  N_GET_CHAT_HISTORY: " N_GET_CHAT_HISTORY"
};
export default API_CONST
