const ACTION_TYPES = {
  //user login action keys
  USER_NAME_CHANGED: "USER_NAME",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  SIGNUP_USER_RES: "SIGNUP_USER_RES",
  SIGNUP_CLEAR_DATA: "SIGNUP_CLEAR_DATA",
  SIGNUP_USER_FB_RES: "SIGNUP_USER_FB_RES",

  //Property

  GET_ALL_PROPERTY_LIST_DATA: "GET_ALL_PROPERTY_LIST_DATA",
  GET_FILTERED_PROPERTY_LIST_DATA: "GET_FILTERED_PROPERTY_LIST_DATA",
  GET_PROPERTY_DETAIL: "GET_PROPERTY_DETAIL",

  // Saved Property
  GET_ALL_SAVED_PROPERTY_LIST_DATA: "GET_ALL_SAVED_PROPERTY_LIST_DATA",

  //Contact
  GET_ACCEEPTED_CONTACT_LIST: "GET_ACCEEPTED_CONTACT_LIST",
  GET_PENDING_CONTACT_LIST: "GET_PENDING_CONTACT_LIST",
  GET_REJECTED_CONTACT_LIST: "GET_REJECTED_CONTACT_LIST",

  //Inspectoion
  POST_INSPECTION_REQUEST: "POST_INSPECTION_REQUEST",
  POST_INSPECTION_BOOK_TIME_REQUEST: "POST_INSPECTION_BOOK_TIME_REQUEST",

  GET_UPCOMING_INSPECTION_LIST: "GET_UPCOMING_INSPECTION_LIST",
  GET_PENDING_INSPECTION_LIST: "GET_PENDING_INSPECTION_LIST",
  GET_DECLINED_INSPECTION_LIST: "GET_DECLINED_INSPECTION_LIST",

  //Setting
  GET_ALL_NOTIFICATION: "GET_ALL_NOTIFICATION",

  //Knowledge
  GET_KNOWLEDGE_LIST: "GET_KNOWLEDGE_LIST",

  //Service
  GET_SERVICE_LIST: "GET_SERVICE_LIST",

  //KnowledgeDetail
  GET_KNOWLEDGE_DETAIL: "GET_KNOWLEDGE_DETAIL",

  //Notification List
  GET_NOTIFICATION_LIST: "GET_NOTIFICATION_LIST",

  //PaymentReportList
  GET_PAYMENT_REPORT_LIST: "GET_PAYMENT_REPORT_LIST",

  //Setting
  GET_CHAT_HISTORY: "GET_CHAT_HISTORY",

  FETCHING_DATA: "FETCHING_DATA",
  RESET_DATA: "RESET_DATA",
  IS_LOADING: "IS_LOADING",
  CLEAR_KID_DATA: "CLEAR_KID_DATA",

  FIRST_NAME_CHANGED: "FIRST_NAME_CHANGED",
  LAST_NAME_CHANGED: "LAST_NAME_CHANGED",
  EMAIL_CHANGED: "EMAIL_CHANGED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  CLEAR_RESPONSE: "CLEAR_RESPONSE",
  CLEAR_LIST: "CLEAR_LIST",
  RESET_DATA: "RESET_DATA",
  FETCH_SIGNUP_RESPONSE_DATA: "FETCH_SIGNUP_RESPONSE_DATA",
  SERVICE_PREF_RES: "SERVICE_PREF_RES",
  SERVICE_PREF_OPTION: "SERVICE_PREF_OPTION",
  CLEAR_SUCCESS_RESPONSE: "CLEAR_SUCCESS_RESPONSE",
  RESET_DATA_BILLING_INFO: "RESET_DATA_BILLING_INFO",

  RESET_DATA_SHIPPING: "RESET_DATA_SHIPPING",

  NAME_CHANGED: "NAME_CHANGED",
  DOB_CHANGED: "DOB_CHANGED",
  GENDER_CHANGED: "GENDER_CHANGED",
  SIZE_CHANGED: "SIZE_CHANGED",
  PROPORTION_CHANGED: "PROPORTION_CHANGED",
  FIT_SIZE_CHANGED: "FIT_SIZE_CHANGED",
  OTHER_BRAND_CHANGED: "OTHER_BRAND_CHANGED",
  BRAND_CHANGED: "BRAND_CHANGED",

  //pregnancy selection

  PREGNANCY_SELECTION_RES: "PREGNANCY_SELECTION_RES",

  //Kids selection

  KIDS_SELECTION_RES: "KIDS_SELECTION_RES",
  BRAND_NAME_CHANGED: "BRAND_NAME_CHANGED",
  BRAND_LIST_RES: "BRAND_LIST_RES",
  WHAT_TO_BUY_RES: "WHAT_TO_BUY_RES",
  NEW_BRAND_LIST_RES: "NEW_BRAND_LIST_RES",

  //size and proportin

  SIZE_AND_PROPORTION_RES: "SIZE_AND_PROPORTION_RES",
  SEND_DATA_RES: "SEND_DATA_RES",
  SEND_BRAND_DATA_RES: "SEND_BRAND_DATA_RES",
  TALK_TO_US_RES: "TALK_TO_US_RES",
  FEEDBACK_CHANGED: "FEEDBACK_CHANGED",

  NEW_SIZE_AND_PROPORTION_RES: "NEW_SIZE_AND_PROPORTION_RES",

  //child Infromation
  FETCH_CHILD_INFO_RESPONSE_DATA: "FETCH CHILD INFO RESPONSE DATA",
  CHILD_NAME_CHANGED: "CHILD NAME CHANGED",
  CHILD_INFO_RESPONSE: "CHILD INFO RESPONSE",

  //pregnancy selection
  PREGNANCY_SELECTION_RES: "PREGNANCY_SELECTION_RES",
  PREGNANCY_DUEDATE_RESPONSE: "PREGNANCY_DUEDATE_RESPONSE",

  //style info
  STYLE_LIST_RES: "STYLE_LIST_RES",

  KIDS_BOX_LIST_RES: "KIDS_BOX_LIST_RES",

  //payment integration

  MAKE_PAYMENT_RES: "MAKE_PAYMENT_RES",
  VALIDATE_USER: "VALIDATE_USER",
  VALIDATE_USER_FB: "VALIDATE_USER_FB",
  MAKE_GIFT_PAYMENT_RES: "MAKE_GIFT_PAYMENT_RES",
  MAKE_GIFT_PAYMENT_RES_AFTER_LOGIN: "MAKE_GIFT_PAYMENT_RES_AFTER_LOGIN",

  STYLE_LIST_RES: "STYLE_LIST_RES",
  GET_PROFILE: "GET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  GET_LAST_BOX: "GET_LAST_BOX",
  UPDATE_IMAGE: "UPDATE_IMAGE",
  UPDATE_KID_IMAGE: "UPDATE_KID_IMAGE",
  UPDATE_KID: "UPDATE_KID",

  //sourabh

  CHECK_SCREEN_RES: "CHECK_SCREEN_RES",

  //style info
  STYLE_LIST_RES_NEW: "STYLE_LIST_RES_NEW",
  SELECTED_STYLE_LIST_RES: "SELECTED_STYLE_LIST_RES",
  SELECTED_STYLE_LIST_RES_NEW: "SELECTED_STYLE_LIST_RES_NEW",

  //BILLING ADDRESS INFORMATION
  ADRESS_CHANGED: "ADRESS_CHANGED",
  CITY_CHANGED: "CITY_CHANGED",
  STATE_CHANGED: "STATE_CHANGED",
  ZIPCODE_CHANGED: "ZIPCODE_CHANGED",
  PHONE_NUMBER_CHANGED: "PHONE_NUMBER_CHANGED",
  BILLING_ADDRESS_RES: "BILLING_ADDRESS_RES",
  SAME_ADDRESS_CHECK: "SAME_ADDRESS_CHECK",

  //BILLING SHIPMENT
  ADRESS_SHIPMENT_CHANGED: "ADRESS_SHIPMENT_CHANGED",
  CITY_SHIPMENT_CHANGED: "CITY_SHIPMENT_CHANGED",
  STATE_SHIPMENT_CHANGED: "STATE_SHIPMENT_CHANGED",
  ZIPCODE_SHIPMENT_CHANGED: "ZIPCODE_SHIPMENT_CHANGED",
  PHONE_NUMBER_SHIPMENT_CHANGED: "PHONE_NUMBER_SHIPMENT_CHANGED",
  BILLING_SHIPMENT_ADDRESS_RES: "BILLING_SHIPMENT_ADDRESS_RES",

  // REFER SCREEN
  CHECK_EMAIL_EXIST: "CHECK_EMAIL_EXIST",
  CHECK_EMAIL_EXIST_GIFT: "CHECK_EMAIL_EXIST_GIFT",

  REFER_FRIEND: "REFER_FRIEND",
  GET_REFERED_LIST: "GET_REFERED_LIST",

  SEND_SOCIAL_INFO: "SEND_SOCIAL_INFO",
  REMOVE_KID: "REMOVE_KID",
  KID_LIST: "KID_LIST",
  REDEEM_AMOUNT: "REDEEM_AMOUNT",
  USER_REDEEM_POINTS: "USER_REDEEM_POINTS",

  ERROR_OCCURRED: "ERROR_OCCURRED",
  CLEAR_ERROR: "CLEAR_ERROR",

  CHECK_REFERRAL_RES: "CHECK_REFERRAL_RES",
  REFERRAL_CODE_CHANGED: "REFERRAL_CODE_CHANGED",

  CHECKOUT_RES: "CHECKOUT_RES",

  _GET_PROFILE: "_GET_PROFILE",
  UPDATE_ADDRESS_RESPONSE: "UPDATE_ADDRESS_RESPONSE",
  ORDER_HISTORY: "ORDER_HISTORY",
  CHECKOUT_RES: "CHECKOUT_RES",
  FORGOT_PASSWORD_RES: "FORGOT_PASSWORD_RES",
  CLEAR_DELETE_RESPONSE: "CLEAR_DELETE_RESPONSE",

  ACTIVE_SUBSCRIPTION: "ACTIVE_SUBSCRIPTION",
  CANCLE_SUBSCRIPTION: "CANCLE_SUBSCRIPTION",

  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CLEAR_CHANGE_PASS_RES: "CLEAR_CHANGE_PASS_RES",
  GET_CREDIT_LIST_RES: "GET_CREDIT_LIST_RES",
  SIZE_SWAP: "SIZE_SWAP",
  BOX_FREQ: "BOX_FREQ",
  REQUEST_BOX: "REQUEST_BOX",

  LOGOUT_USER: "LOGOUT_USER",
  CLEAR_DATA: "CLEAR_DATA",
  CLEAR_FORGOT_PASSWORD: "CLEAR_FORGOT_PASSWORD",
  N_USER_RESET_PROFILE_PIC: "N_USER_RESET_PROFILE_PIC",

  CLEAR_GET_PROFILE_RESPONSE: "CLEAR_GET_PROFILE_RESPONSE",
  CLEAR_UPDATE_PROFILE_RESPONSE: "CLEAR_UPDATE_PROFILE_RESPONSE",

  N_RESET_PROPERTY_LIST_RESPONSE: "N_RESET_PROPERTY_LIST_RESPONSE"
};

export default ACTION_TYPES
